### ISSUE TITLE
Embed CKAN-Service in Catalogue-service

### ISSUE THREAD

**Issue by Kohlroulade** [fraunhoferfokus/GovData#1]
Within the project Energic_OD from European Commision I am planning to integrate your catalogue-service into my own one using the CKAN-protocol. However when I use https://www.govdata.de as endpoint I do not get any results. So I wonder which is the correct URL for integrating the service into my application?

**Comment by benjamindittwald** [comment]
You can access the GovData CKAN API via 

```
https://www.govdata.de/ckan/
```

Here is a simple example:

```
https://www.govdata.de/ckan/api/action/package_show?id=sponsoringberichte-bn
```

For more information on how to use the CKAN API, please refer to the CKAN documentation: http://docs.ckan.org/en/ckan-1.8.2/

**Comment by Kohlroulade** [comment]
Thanks for the hint. However I have a comment. 
According to the examples from http://docs.ckan.org/en/latest/api/ there should be an action that lists all the datasets. However when I make a request to that URL for your app (using https://govdata.de/ckan/api/3/action/package_list) I get 

> Fehlerhafte Anfrage - JSON Fehler: No request body data

However when I enter `https://govdata.de/ckan/api/3/action/package_list?q=` I get the list. So I suggest to return a full list of datasets if no parameters are given to be consistent to the docs from CKAN.

Anyway many thanks for the great portal.

**Comment by benjamindittwald** [comment]
You are welcome.

Please be aware that GovData currently uses CKAN version 1.8.2. There might be changes in the API. Unfortunately I cannot check at the moment, because there seems to be an issue with the CKAN docs for 1.8.2.

http://docs.ckan.org/en/ckan-1.8.2/api/index.html
![screen shot 2015-11-18 at 16 43 32](https://cloud.githubusercontent.com/assets/3661420/11245543/8bf3089a-8e13-11e5-968c-ac4a748e1c86.png)
